void objstart(void);
void newobj(s16, s16, u16, u16);
void objend(void);
void palinit(void);
void bildinit(void);
void newbullet(int,int,int,int,int);
void movebullets(void);
void spawn(void);
u32 rand(void);
void moveenemy(void);
void gameover(void);
void treffer(void);
void schaden(int);
void newobjscal(s16, s16, u16 , u16 , s16,s16);
void newenemy(int,int,int);
void levelup(void);
void newitem(int,int);
void moveitem(void);
void itemwirkung(void);
void missionerfuellt(void);
void load(void);
void save(void);
int count(int);
